on:
  - pull_request

name: Python Lint
jobs:
  python-lint:
    name: Run Python Lint
    runs-on: self-hosted
    strategy:
      matrix:
        #linter: [flake8, pylint, ruff, mypy, pytype, pyright, fixit, pyre]
        linter: [flake8, pylint]
    steps:
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: ${{ matrix.linter }}
