---
on:  # yamllint disable-line rule:truthy
  - pull_request

name: Python Lint
jobs:
  python-lint:
    name: Run Python Lint
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/github-linters:v1
      options: -u 2025:2025
    steps:
      - uses: actions/checkout@v4
      - name: python-lint
        run: |
          find . -name '*.py' -printf '%P\n' | xargs pylint --output-format github
