on: pull_request

name: YAML Lint
jobs:
  yaml-lint:
    name: Run YAML Lint
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/docker-images/linters:v1
      options: -u 2025:2025
    steps:
      - name: yaml-lint
        run: yamllint --format github .

